version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: maven
    directory: /scan-api
    schedule:
      interval: monthly
    groups:
      backend-dependencies:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /scan-app
    schedule:
      interval: monthly
    groups:
      frontend-dependencies:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    groups:
      container-images:
        patterns: ["*"]
